FROM alpine:3.5

MAINTAINER Miguel Eduardo Gil Biraud <miguel.gil.biraud@ieee.org>

ADD https://github.com/kelseyhightower/confd/releases/download/v0.11.0/confd-0.11.0-linux-amd64 /bin/confd

RUN chmod +x /bin/confd

