FROM node:alpine

MAINTAINER Miguel Eduardo Gil Biraud <miguel.gil.biraud@ieee.org>

RUN npm install babel-loader babel-core babel-preset-es2015 webpack webpack-dev-server --save-dev

VOLUME /app

EXPOSE 3000

WORKDIR /app

